language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

before_install:
  - git submodule update --init --recursive
  - git clone git://github.com/maxmind/libmaxminddb
  - cd libmaxminddb
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - pip install pylint coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script:
  - CFLAGS="-Werror -Wall -Wextra" python setup.py test
  - MAXMINDDB_PURE_PYTHON=1 coverage run --source=maxminddb setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pylint --rcfile .pylintrc maxminddb/*.py; fi

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
